### ISSUE TITLE
Модель пользовательского приложения

### ISSUE THREAD

**Issue by ghost** [LeagueOfDevelopers/Today_User#3]

**Comment by Sovent** [comment]
Сообщения по какому принципу показываются в итоге? Рандомно, по таймеру, по алфавиту, как?

**Comment by ghost** [comment]
Рандомное сообщение из тех, которые не отвергнул пользователь, приложение рандомно генерирует 3-4(или n в настройках, посмотрим) временных точек, в которых нужно его отобразить. Допустим, что пользователь выключил ПК и сообщение не отобразилось по расписанию. Тогда, к примеру, через минуту после включения ПК и если последнее отображение сообщения было более часа назад отобразим некоторое сообщение.
