### ISSUE TITLE
Local Log

### ISSUE THREAD

**Issue by ghost** [LeagueOfDevelopers/Today_User#9]
Продумать и реализовать локальный лог действий пользователя. Необходимо для "неназойливого" отображения сообщений.

**Comment by Sovent** [comment]
Каких именно действий? В ОС?

**Comment by ghost** [comment]
В основном это нужно чтобы отследить сколько раз за сегодня (и когда) было отображено сообщение.

**Comment by Sovent** [comment]
N - кол-во сообщений, m(n) - кол-во показов сообщения n, P(n) - вероятность показа сообщения n. 
Предлагаю хранить "вес" сообщения W(n) и вероятность считать, как P(n) = W(n) / (W(0) + W(1) + ... + W(N-1)).
Сам вес считать как W(n) = 1 / ( 1 + m(n)^x), где x - настраиваемая величина, которую можно вынести в Setting как "неповторяемость сообщений" и даже вынести в пользовательские настройки.
Показы можно сбрасывать, либо разово в какой-то промежуток времени (каждый день, например), либо плавно на протяжении всей работы (каждый новый показ уменьшает кол-во всех остальных показов на единицу до минимума 0, например).
Выбор случайного сообщения, основываясь на его вероятности, по идее не должен вызвать затруднений.
